### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-rails-activerecord-models#2]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://sheltered-falls-6096.herokuapp.com/books) and meets the following [project](http://lansingcodelab.com/lessons/rails-activerecord-models/1) criteria:
- [x] Users can search your database through a form on your model's `index` page
- [x] Fields exist in your search for all the attributes in your model, including `created_at` and `updated_at` (but not including `id`) - [Rails form tag helpers](http://api.rubyonrails.org/classes/ActionView/Helpers/FormTagHelper.html) will be useful for this

**Comment by chrisvfritz** [comment]
I only see [a single line](https://github.com/KatieMFritz/codelab-rails-activerecord-models/blob/7681812bcb274f6b37692831445a90c907417234/app/controllers/books_controller.rb#L15) that could be improved:

``` ruby
@books = @books.where('rating >= ?', "#{params[:min_rating]}")
```

Since `params[:min_rating]` is a string,  `"#{params[:min_rating]}"` does the same thing as `params[:min_rating]`. What you're doing is injecting a string into another, otherwise empty string. Does that make sense?

And then I also want to offer you an optional challenge. Right now, you can filter to only include ebooks, but what if users also wanted the ability to filter to only include _non_-ebooks. How could we modify the search to accommodate them?

**Comment by KatieMFritz** [comment]
So should it be 

 `@books = @books.where('rating >= ?', params[:min_rating])`

instead?

**Comment by chrisvfritz** [comment]
Yep, that's right!

**Comment by KatieMFritz** [comment]
Cool. I opt not to do the optional challenge but I incorporated that change into my code. Squirreltime?

**Comment by chrisvfritz** [comment]
:shipit: !
